# Generated by Django 2.1.7 on 2019-03-31 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0006_auto_20190331_0648'),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('exp_date', models.DateField()),
                ('batch_no', models.IntegerField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
                ('unit_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.Unit')),
            ],
        ),
    ]
