# Generated by Django 2.1.7 on 2019-03-31 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20190331_1827'),
        ('stock', '0002_remove_stock_unit_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stock',
            new_name='Sttock',
        ),
    ]
