# Generated by Django 2.1.7 on 2019-03-31 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20190331_1827'),
        ('stock', '0003_auto_20190331_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('exp_date', models.DateField()),
                ('batch_no', models.IntegerField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
            ],
        ),
        migrations.RemoveField(
            model_name='sttock',
            name='item_id',
        ),
        migrations.DeleteModel(
            name='Sttock',
        ),
    ]
