# Generated by Django 2.1.7 on 2019-04-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_auto_20190331_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='quantity',
            new_name='loose_qty',
        ),
        migrations.AddField(
            model_name='stock',
            name='no_of_units',
            field=models.IntegerField(default=0),
        ),
    ]
