# Generated by Django 2.1.7 on 2019-04-06 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_auto_20190406_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.Item'),
        ),
    ]
