# Generated by Django 2.1.7 on 2019-04-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_auto_20190406_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
