# Generated by Django 2.1.7 on 2019-04-14 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20190413_0359'),
        ('stock', '0008_stock_mrp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('item_id', 'batch_no')},
        ),
    ]
