# Generated by Django 2.1.7 on 2019-03-30 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('manufacturer', models.CharField(max_length=70)),
                ('description', models.CharField(max_length=300)),
                ('rackno', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Item_to_Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_qty', models.IntegerField()),
                ('MRP', models.IntegerField()),
                ('Discount', models.IntegerField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('exp_date', models.DateField()),
                ('batch_no', models.IntegerField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('tablet', 'tablet'), ('capsule', 'capsule'), ('injection', 'injection'), ('pouch', 'pouch'), ('bottle', 'bottle'), ('other', 'other')], max_length=15)),
                ('per_unit', models.IntegerField()),
                ('unit', models.CharField(choices=[('mg', 'mg'), ('ml', 'ml')], max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='unit_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.Unit'),
        ),
        migrations.AddField(
            model_name='item_to_unit',
            name='unit_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.Unit'),
        ),
    ]
