# Generated by Django 2.1.7 on 2019-03-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_remove_unit_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_to_unit',
            name='MRP',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
