# Generated by Django 2.1.7 on 2019-03-31 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_auto_20190331_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='unit_id',
        ),
        migrations.DeleteModel(
            name='stock',
        ),
    ]
