# Generated by Django 2.1.7 on 2019-03-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_stock_unit_id'),
        ('items', '0006_auto_20190331_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item_to_unit',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='item_to_unit',
            name='unit_id',
        ),
        migrations.AddField(
            model_name='item',
            name='MRP',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='min_qty',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='item',
            name='per_unit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('tablet', 'tablet'), ('capsule', 'capsule'), ('injection', 'injection'), ('pouch', 'pouch'), ('bottle', 'bottle'), ('other', 'other')], default='tablet', max_length=15),
        ),
        migrations.DeleteModel(
            name='Item_to_Unit',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
