# Generated by Django 2.1.7 on 2019-03-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20190331_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('tablet', 'tablet'), ('capsule', 'capsule'), ('injection', 'injection'), ('pouch', 'pouch'), ('bottle', 'bottle'), ('other', 'other')], max_length=15),
        ),
    ]
