# Generated by Django 2.1.7 on 2019-04-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20190331_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total_loose_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='total_no_of_units',
            field=models.IntegerField(default=0),
        ),
    ]
