# Generated by Django 2.2.1 on 2019-05-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_auto_20190419_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='concentration',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
