# Generated by Django 2.2.1 on 2019-05-07 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_item_concentration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='concentration',
        ),
    ]
