# Generated by Django 2.1.7 on 2019-04-06 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_auto_20190401_1432'),
        ('items', '0008_auto_20190331_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('est_date_of_del', models.DateField()),
                ('act_date_of_del', models.DateField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('supplier_id', models.ForeignKey(on_delete=models.SET('not available'), to='accounts.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Order_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.IntegerField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batchno', models.CharField(max_length=10)),
                ('exp_date', models.DateField()),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Supply_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Supplier')),
            ],
        ),
    ]
