# Generated by Django 2.1.7 on 2019-04-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_auto_20190406_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='act_date_of_del',
        ),
        migrations.RemoveField(
            model_name='order',
            name='est_date_of_del',
        ),
        migrations.AlterField(
            model_name='order',
            name='gtotal',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='batchno',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='order_items',
            name='exp_date',
            field=models.DateField(null=True),
        ),
    ]
