# Generated by Django 2.1.7 on 2019-04-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_auto_20190407_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='gtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
