# Generated by Django 2.1.7 on 2019-04-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_auto_20190407_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply_product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
