# Generated by Django 2.1.7 on 2019-03-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190323_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=150)),
                ('email_id', models.EmailField(max_length=50)),
                ('phone_no', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=70)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Worker', 'Worker')], default='Worker', max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
