# Generated by Django 2.1.7 on 2019-03-24 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190324_0631'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserReg',
            new_name='User',
        ),
    ]
