# Generated by Django 2.1.7 on 2019-03-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190330_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=150)),
                ('email_id', models.EmailField(max_length=50)),
                ('phone_no', models.IntegerField()),
            ],
        ),
    ]
