# Generated by Django 2.1.7 on 2019-04-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190401_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='l_name',
        ),
        migrations.AddField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
