# Generated by Django 2.1.7 on 2019-04-17 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0009_auto_20190413_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=60)),
                ('c_phone', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('gtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_units', models.IntegerField()),
                ('loose_qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batchno', models.CharField(max_length=10, null=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('exp_date', models.DateField(null=True)),
                ('invoice_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.Invoice')),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.Item')),
            ],
        ),
    ]
